#pragma once
#define MOUSE_TOGGLE 0
#define MOUSE_EXIT 1
#define MOUSE_DRAG 2
#define MOUSE_LEFT_CLICK 3
#define MOUSE_RIGHT_CLICK 4
#define MOUSE_MIDDLE_CLICK 5
#define MOUSE_LEFT 6
#define MOUSE_DOWN 7
#define MOUSE_UP 8
#define MOUSE_RIGHT 9
#define MOUSE_SCROLL_LEFT 10
#define MOUSE_SCROLL_DOWN 11
#define MOUSE_SCROLL_UP 12
#define MOUSE_SCROLL_RIGHT 13
#define MOUSE_PRECISE 14
#define MOUSE_FAST 15
