# Enable mouse support
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_MOUSE_ACCELERATION=y

# Movement tuning
CONFIG_ZMK_MOUSE_MOVE_STEP=800
CONFIG_ZMK_MOUSE_SCROLL_STEP=15

CONFIG_ZMK_MOUSE_ACCELERATION_EXPONENT=2
CONFIG_ZMK_MOUSE_ACCELERATION_TIME_MS=40
